name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: '18.14.0'
      
      - uses: pnpm/action-setup@v2
        with:
          version: '6.0.2'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Build
        run: pnpm run build
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: '18.14.0'
      
      - uses: pnpm/action-setup@v2
        with:
          version: '6.0.2'

      - name: Install Dependencies
        run: pnpm install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}